create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  payment text not null,
  items jsonb not null,
  total numeric(12,2) not null,
  status text not null default 'NEW',
  created_at timestamptz not null default now()
);
alter table public.orders enable row level security;
create policy "public can create orders" on public.orders for insert to anon with check (true);
create policy "public can read orders" on public.orders for select to anon using (true);
create policy "public can update orders" on public.orders for update to anon using (true) with check (true);
alter publication supabase_realtime add table public.orders;
